### ISSUE TITLE
Create an interchange format for defining tournaments

### ISSUE THREAD

**Issue by eurochriskelly** [eurochriskelly/gaelic-cup-planner#28]
Using yaml or toml or similar, create format for defining, fixtures and rules for applying pitch, umpires etc. An import format that's reasonably easy to define.

**Comment by eurochriskelly** [comment]
This has been done and documented in separate repo gaelic-cup-builder. An example of the working format is here: 

https://raw.githubusercontent.com/eurochriskelly/gaelic-cup-builder/main/src/sample.yaml

There is a high possibility that all "gcp" repos will be renamed in the future so here is the sample a 

```
tournamentId: 6
description: "Benelux round A"
startDate: "2024-04-01"
pitches: ["Pitch 5", "Pitch 11", "Pitch 12", "Pitch 13"] 
categories:
  Mens:
    g1: ["Amsterdam A", "Groningen", "Leuven A", "Hamburg/Bel'B'", "Eindhoven"]
    g2: ["Luxembourg A", "Nijmegen", "Hague A", "Dusseldorf/Cologne"]
    g3: ["Belgium A", "Leuven B", "Maastricht", "Frankfurt"]
  Ladies:
    g1: ["Leuven A", "A'dam'B'/Leuven'B'", "Belgium A", "Groningen", "Nijmegen"]
    g2: ["Luxembourg A", "Hague/Frankfurt","Hamb/Duss/Lux'B'","Amsterdam A"]
schedule:
  headings: ["startTime", "pitch", "stage", "category", "group", "Team1", "Team2", "UmpireTeam", "Duration"]
  fixtures:
    - ["10:30", "Pitch 5", "group", "Mens", "g1", "Amsterdam A", "Leuven A", "Groningen", 15]
    - ["11:00", "Pitch 5", "group", "Mens", "g3", "Belgium B", "Leuven B", "Leuven A", 20]
    - ["11:30", "Pitch 5", "group", "Mens", "g1", "Leuven A", "Groningen", "Belgium A", 15]
```
